export const essentials = [
  {
    category: "Clothing",
    name: "Formal Clothing",
    packed: false,
    essential: true,
    not_needed: false,
    link: "https://www.amazon.in/gp/search?ie=UTF8&tag=1122088-21&linkCode=ur2&linkId=5c9f7e02ed7634b76ac80dfffc077a40&camp=3638&creative=24630&index=apparel&keywords=Formal Clothing",
    id: "qWIxDKtitU",
  },
  {
    category: "Clothing",
    name: "Ties (for Men)",
    packed: false,
    essential: true,
    not_needed: false,
    link: "https://www.amazon.in/gp/search?ie=UTF8&tag=1122088-21&linkCode=ur2&linkId=eab8d5b8a773b83513d9c3a79238544f&camp=3638&creative=24630&index=apparel&keywords=Ties (for Men)",
    id: "jq7db0L7oK",
  },
  {
    category: "Clothing",
    name: "Undergarments",
    packed: false,
    essential: true,
    not_needed: false,
    link: "https://www.amazon.in/gp/search?ie=UTF8&tag=1122088-21&linkCode=ur2&linkId=e9e696fc807bff4014b90d078c603a0a&camp=3638&creative=24630&index=apparel&keywords=Undergarment",
    id: "i6N2Of0qcD",
  },
  {
    category: "Clothing",
    name: "Winter Jacket",
    packed: false,
    essential: true,
    not_needed: false,
    link: "https://www.amazon.in/gp/search?ie=UTF8&tag=1122088-21&linkCode=ur2&linkId=b1cb1f7d16bd95b0080d359b27577738&camp=3638&creative=24630&index=apparel&keywords=Winter Jacket",
    id: "KVPWE6vf78",
  },
  {
    category: "Clothing",
    name: "Rain Coat",
    packed: false,
    essential: true,
    not_needed: false,
    link: "https://www.amazon.in/gp/search?ie=UTF8&tag=1122088-21&linkCode=ur2&linkId=969c893c9412556b05d45ffc9ad34249&camp=3638&creative=24630&index=apparel&keywords=Rain Coat",
    id: "UmLIHrDt6d",
  },
  {
    category: "Clothing",
    name: "Sweaters",
    packed: false,
    essential: true,
    not_needed: false,
    link: "https://www.amazon.in/gp/search?ie=UTF8&tag=1122088-21&linkCode=ur2&linkId=878c24c061fd6a8ed1d7b40c2018300e&camp=3638&creative=24630&index=apparel&keywords=Sweaters",
    id: "Sa3k5VeHPC",
  },
  {
    category: "Clothing",
    name: "Nightwear",
    packed: false,
    essential: true,
    not_needed: false,
    link: "https://www.amazon.in/gp/search?ie=UTF8&tag=1122088-21&linkCode=ur2&linkId=80c6bebaf19f764d46a033f46798c951&camp=3638&creative=24630&index=apparel&keywords=Nightwear",
    id: "nVilUzVIsK",
  },
  {
    category: "Clothing",
    name: "Jeans",
    packed: false,
    essential: true,
    not_needed: false,
    link: "https://www.amazon.in/gp/search?ie=UTF8&tag=1122088-21&linkCode=ur2&linkId=6ec2f5dc74d9961bab0d5c47261e81b8&camp=3638&creative=24630&index=apparel&keywords=Jeans",
    id: "qHthZW4TMq",
  },
  {
    category: "Clothing",
    name: "T-shirts",
    packed: false,
    essential: true,
    not_needed: false,
    link: "https://www.amazon.in/gp/search?ie=UTF8&tag=1122088-21&linkCode=ur2&linkId=2ebf1d17c7243aa4efcdb31ef73f2fd7&camp=3638&creative=24630&index=apparel&keywords=tshirts",
    id: "1xJUe1W2Xq",
  },
  {
    category: "Clothing",
    name: "Gloves",
    packed: false,
    essential: true,
    not_needed: false,
    link: "https://www.amazon.in/gp/search?ie=UTF8&tag=1122088-21&linkCode=ur2&linkId=0987a6d92edbd8b3fe05d5db0a281def&camp=3638&creative=24630&index=apparel&keywords=Gloves",
    id: "wSy8JfEWCR",
  },
  {
    category: "Clothing",
    name: "Bath Towels",
    packed: false,
    essential: true,
    not_needed: false,
    link: "https://www.amazon.in/gp/search?ie=UTF8&tag=1122088-21&linkCode=ur2&linkId=31ade5d17a64665ba0c8cf706b0a86aa&camp=3638&creative=24630&index=apparel&keywords=Bath Towels",
    id: "1TvGJwizKQ",
  },
  {
    category: "Clothing",
    name: "Thermal Wear",
    packed: false,
    essential: false,
    not_needed: false,
    link: "https://www.amazon.in/gp/search?ie=UTF8&tag=1122088-21&linkCode=ur2&linkId=f228ec8cdc339b6e233b4d39cc4c99f4&camp=3638&creative=24630&index=apparel&keywords=Thermal Wear",
    id: "t9fH4UtLOd",
  },
  {
    category: "Clothing",
    name: "Scarf/Muffler",
    packed: false,
    essential: false,
    not_needed: false,
    link: "https://www.amazon.in/gp/search?ie=UTF8&tag=1122088-21&linkCode=ur2&linkId=6027bb9daa6ac7825a9f90de0379257c&camp=3638&creative=24630&index=apparel&keywords=Muffler",
    id: "1zVJtnOwvG",
  },
  {
    category: "Clothing",
    name: "Shorts",
    packed: false,
    essential: false,
    not_needed: false,
    link: "https://www.amazon.in/gp/search?ie=UTF8&tag=1122088-21&linkCode=ur2&linkId=04831f9396d65d53aacbd7e6c78488f3&camp=3638&creative=24630&index=apparel&keywords=Shorts",
    id: "1RxSvcd5NX",
  },
  {
    category: "Clothing",
    name: "Swimming Trunks",
    packed: false,
    essential: false,
    not_needed: false,
    link: "https://www.amazon.in/gp/search?ie=UTF8&tag=1122088-21&linkCode=ur2&linkId=80336cc7b6bcacc196f8fb42dc203aa5&camp=3638&creative=24630&index=apparel&keywords=Swimming Trunks",
    id: "uJUWBW6SLy",
  },
  {
    category: "Clothing",
    name: "Sports Wear",
    packed: false,
    essential: false,
    not_needed: false,
    link: "https://www.amazon.in/gp/search?ie=UTF8&tag=1122088-21&linkCode=ur2&linkId=0526901dfa14b38fe5f09fbf138e267a&camp=3638&creative=24630&index=apparel&keywords=Sports Wear",
    id: "d6f8a1lZ5q",
  },
  {
    category: "Clothing",
    name: "Belts for Pants",
    packed: false,
    essential: false,
    not_needed: false,
    link: "https://www.amazon.in/gp/search?ie=UTF8&tag=1122088-21&linkCode=ur2&linkId=553fd17554e0269b1496ae31bd93d9a7&camp=3638&creative=24630&index=apparel&keywords=Belts for Pants",
    id: "DLz2eUZtVX",
  },
  {
    category: "Stationary",
    name: "Cello Tape",
    packed: false,
    essential: true,
    not_needed: false,
    link: "https://www.amazon.in/gp/search?ie=UTF8&tag=1122088-21&linkCode=ur2&linkId=15691562242a37fe79a2e1481dcb6526&camp=3638&creative=24630&index=aps&keywords=Cello Tape",
    id: "3ifW6vOZDE",
  },
  {
    category: "Stationary",
    name: "Pens & Pencils",
    packed: false,
    essential: true,
    not_needed: false,
    link: "https://www.amazon.in/gp/search?ie=UTF8&tag=1122088-21&linkCode=ur2&linkId=b6a14080d1a5417e99dbda2684189647&camp=3638&creative=24630&index=aps&keywords=Pens and Pencils",
    id: "B9vIJaaHE1",
  },
  {
    category: "Stationary",
    name: "Eraser",
    packed: false,
    essential: true,
    not_needed: false,
    link: "https://www.amazon.in/gp/search?ie=UTF8&tag=1122088-21&linkCode=ur2&linkId=6d3d6109e218e00f16ed411c0a9ca34b&camp=3638&creative=24630&index=aps&keywords=Eraser",
    id: "Vv8af1mRam",
  },
  {
    category: "Stationary",
    name: "File Folder",
    packed: false,
    essential: true,
    not_needed: false,
    link: "https://www.amazon.in/gp/search?ie=UTF8&tag=1122088-21&linkCode=ur2&linkId=7d25bf73a80154433a694389040b5746&camp=3638&creative=24630&index=aps&keywords=File Folder",
    id: "LnAazxm3gx",
  },
  {
    category: "Stationary",
    name: "Marker",
    packed: false,
    essential: true,
    not_needed: false,
    link: "https://www.amazon.in/gp/search?ie=UTF8&tag=1122088-21&linkCode=ur2&linkId=0dbe2bc9a494fcd936568999e45f8497&camp=3638&creative=24630&index=aps&keywords=Marker",
    id: "xZ9yRpr6qM",
  },
  {
    category: "Stationary",
    name: "Notebooks / Pads",
    packed: false,
    essential: true,
    not_needed: false,
    link: "https://www.amazon.in/gp/search?ie=UTF8&tag=1122088-21&linkCode=ur2&linkId=770ccce626991502d9db32791eb6ab93&camp=3638&creative=24630&index=aps&keywords=Notebooks",
    id: "UI06r0B7IG",
  },
  {
    category: "Stationary",
    name: "Rubber Bands",
    packed: false,
    essential: true,
    not_needed: false,
    link: "https://www.amazon.in/gp/search?ie=UTF8&tag=1122088-21&linkCode=ur2&linkId=efc10d2bcbbc9adba7c4359089ab4120&camp=3638&creative=24630&index=aps&keywords=Rubber Bands",
    id: "Qj8IIpYLyW",
  },
  {
    category: "Stationary",
    name: "Stapler and Pin",
    packed: false,
    essential: true,
    not_needed: false,
    link: "https://www.amazon.in/gp/search?ie=UTF8&tag=1122088-21&linkCode=ur2&linkId=53598c3243327edaabea9a565ddf0401&camp=3638&creative=24630&index=aps&keywords=Stapler and Pin",
    id: "Hxp3ymuUHk",
  },
  {
    category: "Stationary",
    name: "Sticky Notes",
    packed: false,
    essential: true,
    not_needed: false,
    link: "https://www.amazon.in/gp/search?ie=UTF8&tag=1122088-21&linkCode=ur2&linkId=79243ada559ca623fb2ab563b8f8a495&camp=3638&creative=24630&index=aps&keywords=Sticky Notes",
    id: "itRnMj6hFa",
  },
  {
    category: "Stationary",
    name: "Scissors",
    packed: false,
    essential: true,
    not_needed: false,
    link: "https://www.amazon.in/gp/search?ie=UTF8&tag=1122088-21&linkCode=ur2&linkId=8c569e469570690fd6625d7523b26404&camp=3638&creative=24630&index=aps&keywords=Scissors",
    id: "vx9JX5IISt",
  },
  {
    category: "Stationary",
    name: "Paper Clips",
    packed: false,
    essential: true,
    not_needed: false,
    link: "https://www.amazon.in/gp/search?ie=UTF8&tag=1122088-21&linkCode=ur2&linkId=0acf1838060f12c38b47e72fb98bb97c&camp=3638&creative=24630&index=aps&keywords=Paper Clips",
    id: "4b0aYqgDGh",
  },
  {
    category: "Stationary",
    name: "A4 Sheets",
    packed: false,
    essential: true,
    not_needed: false,
    link: "https://www.amazon.in/gp/search?ie=UTF8&tag=1122088-21&linkCode=ur2&linkId=f01fccc6034f6c20be6b9849bd10a2d8&camp=3638&creative=24630&index=aps&keywords=A4 Sheets",
    id: "r91XUjyczX",
  },
  {
    category: "Stationary",
    name: "Highlighter",
    packed: false,
    essential: false,
    not_needed: false,
    link: "https://www.amazon.in/gp/search?ie=UTF8&tag=1122088-21&linkCode=ur2&linkId=d30d3ab932ec694920d92c42f75fcdda&camp=3638&creative=24630&index=aps&keywords=Highlighter",
    id: "6iD8ZmEYAT",
  },
  {
    category: "Stationary",
    name: "Glue",
    packed: false,
    essential: false,
    not_needed: false,
    link: "https://www.amazon.in/gp/search?ie=UTF8&tag=1122088-21&linkCode=ur2&linkId=6460cd1fce0e77e02cbc54ba49aaa514&camp=3638&creative=24630&index=aps&keywords=Glue",
    id: "faydtE5pXP",
  },
  {
    category: "Stationary",
    name: "Pen Holder",
    packed: false,
    essential: false,
    not_needed: false,
    link: "https://www.amazon.in/gp/search?ie=UTF8&tag=1122088-21&linkCode=ur2&linkId=12b47a0e76b924c640a6b7a40cf17566&camp=3638&creative=24630&index=aps&keywords=Pen Holder",
    id: "sB6zbCbjyC",
  },
  {
    category: "Stationary",
    name: "Punching Machine",
    packed: false,
    essential: false,
    not_needed: false,
    link: "https://www.amazon.in/gp/search?ie=UTF8&tag=1122088-21&linkCode=ur2&linkId=f7d56cc083061b0703a56eb3e440f9f6&camp=3638&creative=24630&index=aps&keywords=Punching Machine",
    id: "VHmtW0VHVl",
  },
  {
    category: "Stationary",
    name: "Paper Cutter",
    packed: false,
    essential: false,
    not_needed: false,
    link: "https://www.amazon.in/gp/search?ie=UTF8&tag=1122088-21&linkCode=ur2&linkId=b77c37e698034f0cba76a9cab49bbac5&camp=3638&creative=24630&index=aps&keywords=Paper Cutter",
    id: "nYVS8qCWAK",
  },
  {
    category: "Stationary",
    name: "Labels",
    packed: false,
    essential: false,
    not_needed: false,
    link: "https://www.amazon.in/gp/search?ie=UTF8&tag=1122088-21&linkCode=ur2&linkId=ea0b3de84ea739ea454b5341808362b7&camp=3638&creative=24630&index=aps&keywords=Labels",
    id: "EFEwZT1N3N",
  },
  {
    category: "Stationary",
    name: "Scientific Calculator",
    packed: false,
    essential: false,
    not_needed: false,
    link: "https://www.amazon.in/gp/search?ie=UTF8&tag=1122088-21&linkCode=ur2&linkId=959db2b9c99c7fed70c5c626fc57a316&camp=3638&creative=24630&index=aps&keywords=Scientific Calculator",
    id: "yAQ0CKBIbi",
  },
  {
    category: "Stationary",
    name: "Small Ruler",
    packed: false,
    essential: false,
    not_needed: false,
    link: "https://www.amazon.in/gp/search?ie=UTF8&tag=1122088-21&linkCode=ur2&linkId=c89be4213ff349f2a2cbd3ae72f1851f&camp=3638&creative=24630&index=aps&keywords=Small Ruler",
    id: "5svRNf1SDM",
  },
  {
    category: "Stationary",
    name: "Compass Box / Pouch",
    packed: false,
    essential: false,
    not_needed: false,
    link: "https://www.amazon.in/gp/search?ie=UTF8&tag=1122088-21&linkCode=ur2&linkId=083b27af0df36b7592b8424f6ed1df47&camp=3638&creative=24630&index=aps&keywords=Compass Box Pouch",
    id: "fJ6B7gX4E9",
  },
  {
    category: "Footwear",
    name: "Formal Shoes",
    packed: false,
    essential: true,
    not_needed: false,
    link: "https://www.amazon.in/gp/search?ie=UTF8&tag=1122088-21&linkCode=ur2&linkId=090f4fc70ad5bfe92c757cd330f8fbbc&camp=3638&creative=24630&index=apparel&keywords=Formal Shoes",
    id: "2wj1yucB4M",
  },
  {
    category: "Footwear",
    name: "Sports Shoes",
    packed: false,
    essential: true,
    not_needed: false,
    link: "https://www.amazon.in/gp/search?ie=UTF8&tag=1122088-21&linkCode=ur2&linkId=35a51243e8f181264a6e5d5e751fe9a3&camp=3638&creative=24630&index=apparel&keywords=Sports Shoes",
    id: "MgRT0pKrGL",
  },
  {
    category: "Footwear",
    name: "Casual Shoes",
    packed: false,
    essential: true,
    not_needed: false,
    link: "https://www.amazon.in/gp/search?ie=UTF8&tag=1122088-21&linkCode=ur2&linkId=bd44553ee279bf61002d557a22814344&camp=3638&creative=24630&index=apparel&keywords=Casual Shoes",
    id: "OkZBRiOHO4",
  },
  {
    category: "Footwear",
    name: "Indoor Slippers",
    packed: false,
    essential: true,
    not_needed: false,
    link: "https://www.amazon.in/gp/search?ie=UTF8&tag=1122088-21&linkCode=ur2&linkId=b080c3b8e6eb0ab3720d8dda573c13bc&camp=3638&creative=24630&index=apparel&keywords=Indoor Slippers",
    id: "gXzl54dipM",
  },
  {
    category: "Footwear",
    name: "Socks",
    packed: false,
    essential: true,
    not_needed: false,
    link: "https://www.amazon.in/gp/search?ie=UTF8&tag=1122088-21&linkCode=ur2&linkId=2e003fa635a0e0045e140ac2732fb796&camp=3638&creative=24630&index=apparel&keywords=Socks",
    id: "9fP74kqNAD",
  },
  {
    category: "Footwear",
    name: "Woollen socks (for cold weather)",
    packed: false,
    essential: false,
    not_needed: false,
    link: "https://www.amazon.in/gp/search?ie=UTF8&tag=1122088-21&linkCode=ur2&linkId=12921efe5e3bd8a597a791737adca382&camp=3638&creative=24630&index=apparel&keywords=Woollen socks",
    id: "sXDhqPmNcm",
  },
  {
    category: "Electronics",
    name: "Personal Laptop and Charger",
    packed: false,
    essential: true,
    not_needed: false,
    link: "https://www.amazon.in/gp/search?ie=UTF8&tag=1122088-21&linkCode=ur2&linkId=8b6851742aa7b9c215f5f86a95573fb8&camp=3638&creative=24630&index=eu-ce-in&keywords=Personal Laptop",
    id: "9IHJndSxlY",
  },
  {
    category: "Electronics",
    name: "Mobile Phone and Charger",
    packed: false,
    essential: true,
    not_needed: false,
    link: "https://www.amazon.in/gp/search?ie=UTF8&tag=1122088-21&linkCode=ur2&linkId=36aa711ce7e879684678bdddda18f8bc&camp=3638&creative=24630&index=eu-ce-in&keywords=Mobile Phone",
    id: "NRLYJnPr9V",
  },
  {
    category: "Electronics",
    name: "Table Clock with Alarm Functionality",
    packed: false,
    essential: true,
    not_needed: false,
    link: "https://www.amazon.in/gp/search?ie=UTF8&tag=1122088-21&linkCode=ur2&linkId=9e2601ccf2757fa44d0efcf85e00e211&camp=3638&creative=24630&index=eu-ce-in&keywords=Table Clock with Alarm",
    id: "93YZxWNuhQ",
  },
  {
    category: "Electronics",
    name: "Travel Adaptor",
    packed: false,
    essential: true,
    not_needed: false,
    link: "https://www.amazon.in/rts-Universal-Adapter-International-Worldwide/dp/B082WYMTWF/ref=sr_1_3?crid=2Y92QCBP9HIMM&amp;keywords=Travel+Adaptor&amp;qid=1690392912&amp;sprefix=travel+adaptor%252Caps%252C232&amp;sr=8-3&_encoding=UTF8&tag=1122088-21&linkCode=ur2&linkId=fa405367ac5ef611128c537bb50b7905&camp=3638&creative=24630",
    id: "gcv6z3Vthn",
  },
  {
    category: "Electronics",
    name: "Spike Buster",
    packed: false,
    essential: true,
    not_needed: false,
    link: "https://www.amazon.in/gp/search?ie=UTF8&tag=1122088-21&linkCode=ur2&linkId=413181591cecc8bc3b89402dca8700c5&camp=3638&creative=24630&index=eu-ce-in&keywords=Spike Buster",
    id: "cHKmx8wVkT",
  },
  {
    category: "Electronics",
    name: "Extra Batteries",
    packed: false,
    essential: true,
    not_needed: false,
    link: "https://www.amazon.in/gp/search?ie=UTF8&tag=1122088-21&linkCode=ur2&linkId=07e8e8408fb2bb1d7a92a610d6611572&camp=3638&creative=24630&index=eu-ce-in&keywords=Extra Batteries",
    id: "ubJ8RVShGJ",
  },
  {
    category: "Electronics",
    name: "External Harddisk",
    packed: false,
    essential: false,
    not_needed: false,
    link: "https://www.amazon.in/gp/search?ie=UTF8&tag=1122088-21&linkCode=ur2&linkId=7b85fd1b5040661ddb169d77437890dd&camp=3638&creative=24630&index=eu-ce-in&keywords=External Harddisk",
    id: "ndFXdeilkt",
  },
  {
    category: "Electronics",
    name: "USB Keyboard and Mouse",
    packed: false,
    essential: false,
    not_needed: false,
    link: "https://www.amazon.in/gp/search?ie=UTF8&tag=1122088-21&linkCode=ur2&linkId=f085085d5f7c88543169d8710bf4d175&camp=3638&creative=24630&index=eu-ce-in&keywords=USB Keyboard and Mouse",
    id: "vm8EkeF6Vb",
  },
  {
    category: "Electronics",
    name: "Bluetooth Speakers",
    packed: false,
    essential: false,
    not_needed: false,
    link: "https://www.amazon.in/gp/search?ie=UTF8&tag=1122088-21&linkCode=ur2&linkId=39c7af634b794f0c035f7c57dc8f621d&camp=3638&creative=24630&index=eu-ce-in&keywords=Bluetooth Speakers",
    id: "yaCVFssjf5",
  },
  {
    category: "Electronics",
    name: "Digital Camera",
    packed: false,
    essential: false,
    not_needed: false,
    link: "https://www.amazon.in/gp/search?ie=UTF8&tag=1122088-21&linkCode=ur2&linkId=8252ddbd23b8254c0ecacc81397a0219&camp=3638&creative=24630&index=eu-ce-in&keywords=Digital Camera",
    id: "LerbCuNDDP",
  },
  {
    category: "Electronics",
    name: "Headphones with Mic",
    packed: false,
    essential: false,
    not_needed: false,
    link: "https://www.amazon.in/gp/search?ie=UTF8&tag=1122088-21&linkCode=ur2&linkId=a81db4eafe92e0a410cca89caf28ec2c&camp=3638&creative=24630&index=eu-ce-in&keywords=Headphones with Mic",
    id: "Ow8oWMUWgF",
  },
  {
    category: "Electronics",
    name: "Powerbank",
    packed: false,
    essential: false,
    not_needed: false,
    link: "https://www.amazon.in/gp/search?ie=UTF8&tag=1122088-21&linkCode=ur2&linkId=65c3f74b209ddf9d9e7c0018088f3a70&camp=3638&creative=24630&index=eu-ce-in&keywords=Powerbank",
    id: "pKLH31SfPs",
  },
  {
    category: "Electronics",
    name: "LAN Cable",
    packed: false,
    essential: false,
    not_needed: false,
    link: "https://www.amazon.in/gp/search?ie=UTF8&tag=1122088-21&linkCode=ur2&linkId=0a1f4d27556b8572756b0a115d17e41a&camp=3638&creative=24630&index=eu-ce-in&keywords=LAN Cable",
    id: "kBggKlPaqf",
  },
  {
    category: "Electronics",
    name: "Tripod",
    packed: false,
    essential: false,
    not_needed: false,
    link: "https://www.amazon.in/gp/search?ie=UTF8&tag=1122088-21&linkCode=ur2&linkId=8741548a90105c22102676b6b6ca9691&camp=3638&creative=24630&index=eu-ce-in&keywords=Tripod",
    id: "o4ThNHMACw",
  },
  {
    category: "Electronics",
    name: "Steam Iron",
    packed: false,
    essential: false,
    not_needed: false,
    link: "https://www.amazon.in/gp/search?ie=UTF8&tag=1122088-21&linkCode=ur2&linkId=cc5d50527a2b7727bbd63ebdc8da63af&camp=3638&creative=24630&index=eu-ce-in&keywords=Steam Iron",
    id: "x9UA69RcLq",
  },
  {
    category: "Medicine",
    name: "Crocin",
    packed: false,
    essential: true,
    not_needed: false,
    link: "",
    id: "FEI0f63JEL",
  },
  {
    category: "Medicine",
    name: "Combiflam",
    packed: false,
    essential: true,
    not_needed: false,
    link: "",
    id: "9y0sWXfSj3",
  },
  {
    category: "Medicine",
    name: "Cyclopam",
    packed: false,
    essential: true,
    not_needed: false,
    link: "",
    id: "pIPsSJR9xM",
  },
  {
    category: "Medicine",
    name: "Vicks Vaporub",
    packed: false,
    essential: true,
    not_needed: false,
    link: "https://www.amazon.in/gp/search?ie=UTF8&tag=1122088-21&linkCode=ur2&linkId=6beea647133fd9fa91edef4b4bb02329&camp=3638&creative=24630&index=aps&keywords=Vicks Vaporub",
    id: "KdUCmasIat",
  },
  {
    category: "Medicine",
    name: "Thermometer",
    packed: false,
    essential: true,
    not_needed: false,
    link: "https://www.amazon.in/gp/search?ie=UTF8&tag=1122088-21&linkCode=ur2&linkId=1b6ef0e040f64dff8d632d9b95e3a582&camp=3638&creative=24630&index=aps&keywords=Thermometer",
    id: "ux65DkxeW8",
  },
  {
    category: "Medicine",
    name: "Volini Spray",
    packed: false,
    essential: true,
    not_needed: false,
    link: "https://www.amazon.in/gp/search?ie=UTF8&tag=1122088-21&linkCode=ur2&linkId=82665613a5d6f3a727806239cefbe407&camp=3638&creative=24630&index=aps&keywords=Volini Spray",
    id: "NTQNvKlPVd",
  },
  {
    category: "Medicine",
    name: "Band-Aids",
    packed: false,
    essential: true,
    not_needed: false,
    link: "https://www.amazon.in/gp/search?ie=UTF8&tag=1122088-21&linkCode=ur2&linkId=704b3dd9d8791fe7880325d333da9bda&camp=3638&creative=24630&index=aps&keywords=Band Aids",
    id: "kqNfFE0880",
  },
  {
    category: "Medicine",
    name: "Cotton",
    packed: false,
    essential: true,
    not_needed: false,
    link: "https://www.amazon.in/gp/search?ie=UTF8&tag=1122088-21&linkCode=ur2&linkId=ed96611b3322b3505a8295259fce3849&camp=3638&creative=24630&index=aps&keywords=Cotton",
    id: "uYwxKEkn3W",
  },
  {
    category: "Medicine",
    name: "Salvol/Dentol",
    packed: false,
    essential: true,
    not_needed: false,
    link: "https://www.amazon.in/gp/search?ie=UTF8&tag=1122088-21&linkCode=ur2&linkId=25cdfe94d96d5e6db1347410b4bfd340&camp=3638&creative=24630&index=aps&keywords=Salvol or Dentol",
    id: "1ajqwFkdye",
  },
  {
    category: "Medicine",
    name: "Prescription Medicines",
    packed: false,
    essential: true,
    not_needed: false,
    link: "",
    id: "qWE7Yhh7xu",
  },
  {
    category: "Medicine",
    name: "Avomine",
    packed: false,
    essential: false,
    not_needed: false,
    link: "",
    id: "Icry6YKYxo",
  },
  {
    category: "Medicine",
    name: "Gelucil, Zantac",
    packed: false,
    essential: false,
    not_needed: false,
    link: "",
    id: "hxkk1IiY8H",
  },
  {
    category: "Medicine",
    name: "Lopomide",
    packed: false,
    essential: false,
    not_needed: false,
    link: "",
    id: "Jmcuv5gY0r",
  },
  {
    category: "Medicine",
    name: "Itch Guard",
    packed: false,
    essential: false,
    not_needed: false,
    link: "https://www.amazon.in/gp/search?ie=UTF8&tag=1122088-21&linkCode=ur2&linkId=d9fe561197dc38fd68c3449140389f6d&camp=3638&creative=24630&index=aps&keywords=Itch Guard",
    id: "rRAxpvfXMS",
  },
  {
    category: "Medicine",
    name: "Strepsils",
    packed: false,
    essential: false,
    not_needed: false,
    link: "https://www.amazon.in/gp/search?ie=UTF8&tag=1122088-21&linkCode=ur2&linkId=048a717b260fd1f6ccb688688504dec1&camp=3638&creative=24630&index=aps&keywords=Strepsils",
    id: "ZGbvTgM8X1",
  },
  {
    category: "Medicine",
    name: "Burnol",
    packed: false,
    essential: false,
    not_needed: false,
    link: "https://www.amazon.in/Burnol-reqd-MFR-Dr-Morepen/dp/B0777M4HZM?crid=1QDKN9KYFTQDO&keywords=Burnol&qid=1690393536&sprefix=burnol%2Caps%2C233&sr=8-1&linkCode=ll1&tag=1122088-21&linkId=b0548d151963e59b896f2f52a8db81d4&language=en_IN&ref_=as_li_ss_tl",
    id: "soZZ0p0fPR",
  },
  {
    category: "Medicine",
    name: "Inhaler",
    packed: false,
    essential: false,
    not_needed: false,
    link: "https://www.amazon.in/gp/search?ie=UTF8&tag=1122088-21&linkCode=ur2&linkId=1975285184539816d1bcb7509ea74f80&camp=3638&creative=24630&index=aps&keywords=Inhaler",
    id: "aoMybcpdv6",
  },
  {
    category: "Medicine",
    name: "Benadryl",
    packed: false,
    essential: false,
    not_needed: false,
    link: "link_to_buy_benadryl",
    id: "lqwTI1CBrl",
  },
  {
    category: "Kitchen",
    name: "Pressure Cooker",
    packed: false,
    essential: true,
    not_needed: false,
    link: "https://www.amazon.in/gp/search?ie=UTF8&tag=1122088-21&linkCode=ur2&linkId=56d3e4714a2a03a58710c98fef9443cb&camp=3638&creative=24630&index=kitchen&keywords=Pressure Cooker",
    id: "9sQaxm9egy",
  },
  {
    category: "Kitchen",
    name: "Medium-Sized Pan for Cooking Vegetables",
    packed: false,
    essential: true,
    not_needed: false,
    link: "https://amzn.to/3rNCgpy",
    id: "6DmmQY2fsd",
  },
  {
    category: "Kitchen",
    name: "Serving Spoons of Various Sizes",
    packed: false,
    essential: true,
    not_needed: false,
    link: "https://amzn.to/3DAFJdq",
    id: "6QzDIRV4qm",
  },
  {
    category: "Kitchen",
    name: "Plates",
    packed: false,
    essential: true,
    not_needed: false,
    link: "https://amzn.to/45116Ar",
    id: "JCW0Jb9yr8",
  },
  {
    category: "Kitchen",
    name: "Kadhai for boiling milk/water/rice",
    packed: false,
    essential: true,
    not_needed: false,
    link: "https://amzn.to/3KckQco",
    id: "FcNvRLcFl3",
  },
  {
    category: "Kitchen",
    name: "Knives",
    packed: false,
    essential: true,
    not_needed: false,
    link: "https://amzn.to/473gkqz",
    id: "IHfG0VGJvt",
  },
  {
    category: "Kitchen",
    name: "Stainless Steel Glasses/Tumblers",
    packed: false,
    essential: true,
    not_needed: false,
    link: "https://amzn.to/3Y7Pp8K",
    id: "5Tpfapp0Mr",
  },
  {
    category: "Kitchen",
    name: "Normal Small Spoons and Forks",
    packed: false,
    essential: true,
    not_needed: false,
    link: "https://amzn.to/3rIDN06",
    id: "K6Z25C4ouR",
  },
  {
    category: "Kitchen",
    name: "Water Bottles",
    packed: false,
    essential: true,
    not_needed: false,
    link: "https://www.amazon.in/gp/search?ie=UTF8&tag=1122088-21&linkCode=ur2&linkId=3b9d4d0c80ec901c178244e7c3ac0ff9&camp=3638&creative=24630&index=kitchen&keywords=Water Bottles",
    id: "YJUHtveT6W",
  },
  {
    category: "Kitchen",
    name: "Lunchbox",
    packed: false,
    essential: true,
    not_needed: false,
    link: "https://www.amazon.in/gp/search?ie=UTF8&tag=1122088-21&linkCode=ur2&linkId=ff29cf1ae62169db45f72dfdc0806042&camp=3638&creative=24630&index=kitchen&keywords=Lunchbox",
    id: "C8ituO1cGi",
  },
  {
    category: "Kitchen",
    name: "Can Opener",
    packed: false,
    essential: true,
    not_needed: false,
    link: "https://www.amazon.in/gp/search?ie=UTF8&tag=1122088-21&linkCode=ur2&linkId=ba7d3bbc5b91e22ef26aa78fe84a8ebe&camp=3638&creative=24630&index=kitchen&keywords=Can Opener",
    id: "5viqJFCeGg",
  },
  {
    category: "Kitchen",
    name: "Bowls",
    packed: false,
    essential: true,
    not_needed: false,
    link: "link_to_buy_bowls",
    id: "cEm8Hv0k6O",
  },
  {
    category: "Kitchen",
    name: "Extra Weights and Gaskets for Cookers",
    packed: false,
    essential: false,
    not_needed: false,
    link: "link_to_buy_extra_weights_gaskets",
    id: "3YpjQpTXlH",
  },
  {
    category: "Kitchen",
    name: "Roti Pad & Rolling Pin",
    packed: false,
    essential: false,
    not_needed: false,
    link: "link_to_buy_roti_pad_rolling_pin",
    id: "fsYr6HK59x",
  },
  {
    category: "Kitchen",
    name: "Butter Knives",
    packed: false,
    essential: false,
    not_needed: false,
    link: "link_to_buy_butter_knives",
    id: "XdJ6ltXELx",
  },
  {
    category: "Kitchen",
    name: "Vegetable Chopping Board",
    packed: false,
    essential: false,
    not_needed: false,
    link: "link_to_buy_chopping_board",
    id: "TXDws4jyI2",
  },
  {
    category: "Kitchen",
    name: "Strainers of Various Sizes",
    packed: false,
    essential: false,
    not_needed: false,
    link: "link_to_buy_strainers",
    id: "8jmrWt1Kp2",
  },
  {
    category: "Kitchen",
    name: "Microwave-safe utensils",
    packed: false,
    essential: false,
    not_needed: false,
    link: "link_to_buy_microwave_utensils",
    id: "8KBaBQpxsP",
  },
  {
    category: "Kitchen",
    name: "Vegetable Cutter / Dicer",
    packed: false,
    essential: false,
    not_needed: false,
    link: "link_to_buy_vegetable_cutter",
    id: "wJKzHJR1vd",
  },
  {
    category: "Kitchen",
    name: "Small Mixer",
    packed: false,
    essential: false,
    not_needed: false,
    link: "link_to_buy_small_mixer",
    id: "y2QKm5PW7p",
  },
  {
    category: "PersonalCare",
    name: "Soap Box",
    packed: false,
    essential: true,
    not_needed: false,
    link: "link_to_buy_soap_box",
    id: "j3M5x9W1HL",
  },
  {
    category: "PersonalCare",
    name: "Hand Sanitizer",
    packed: false,
    essential: true,
    not_needed: false,
    link: "link_to_buy_hand_sanitizer",
    id: "MUMpzgDgtE",
  },
  {
    category: "PersonalCare",
    name: "Hand Wash",
    packed: false,
    essential: true,
    not_needed: false,
    link: "link_to_buy_hand_wash",
    id: "TQ6tVh8B3m",
  },
  {
    category: "PersonalCare",
    name: "Hair Oil",
    packed: false,
    essential: true,
    not_needed: false,
    link: "link_to_buy_hair_oil",
    id: "dbl85HTzp7",
  },
  {
    category: "PersonalCare",
    name: "Shampoo",
    packed: false,
    essential: true,
    not_needed: false,
    link: "link_to_buy_shampoo",
    id: "hywmn12DJs",
  },
  {
    category: "PersonalCare",
    name: "Tooth Paste",
    packed: false,
    essential: true,
    not_needed: false,
    link: "link_to_buy_tooth_paste",
    id: "bBXcBNnUHA",
  },
  {
    category: "PersonalCare",
    name: "Tooth Brush",
    packed: false,
    essential: true,
    not_needed: false,
    link: "link_to_buy_tooth_brush",
    id: "eBjoLNyUIf",
  },
  {
    category: "PersonalCare",
    name: "Soap",
    packed: false,
    essential: true,
    not_needed: false,
    link: "link_to_buy_soap",
    id: "i9z1DNKvb4",
  },
  {
    category: "PersonalCare",
    name: "Tissues",
    packed: false,
    essential: true,
    not_needed: false,
    link: "link_to_buy_tissues",
    id: "rY1TDH68Mb",
  },
  {
    category: "PersonalCare",
    name: "Face Wash",
    packed: false,
    essential: true,
    not_needed: false,
    link: "link_to_buy_face_wash",
    id: "xDEhdVDtsO",
  },
  {
    category: "PersonalCare",
    name: "Moisturizer",
    packed: false,
    essential: true,
    not_needed: false,
    link: "link_to_buy_moisturizer",
    id: "quMEdGNcCQ",
  },
  {
    category: "PersonalCare",
    name: "Sun Screen",
    packed: false,
    essential: true,
    not_needed: false,
    link: "link_to_buy_sun_screen",
    id: "0KHIW8bNUh",
  },
  {
    category: "PersonalCare",
    name: "Lip Balm",
    packed: false,
    essential: true,
    not_needed: false,
    link: "link_to_buy_lip_balm",
    id: "xcrr7zVKpm",
  },
  {
    category: "PersonalCare",
    name: "Hair Comb",
    packed: false,
    essential: true,
    not_needed: false,
    link: "link_to_buy_hair_comb",
    id: "9jUAqMBt3D",
  },
  {
    category: "PersonalCare",
    name: "Rubber Bands",
    packed: false,
    essential: true,
    not_needed: false,
    link: "link_to_buy_rubber_bands",
    id: "Tgvt0fcEWY",
  },
  {
    category: "PersonalCare",
    name: "Shaving Razor and Foam",
    packed: false,
    essential: true,
    not_needed: false,
    link: "link_to_buy_shaving_razor_foam",
    id: "xW6OYMUwUo",
  },
  {
    category: "PersonalCare",
    name: "Hair Pins",
    packed: false,
    essential: true,
    not_needed: false,
    link: "link_to_buy_hair_pins",
    id: "j494NacxlL",
  },
  {
    category: "PersonalCare",
    name: "Hair Clips / Bands",
    packed: false,
    essential: true,
    not_needed: false,
    link: "link_to_buy_hair_clips_bands",
    id: "bX9LUTZsX0",
  },
  {
    category: "PersonalCare",
    name: "Nail Cutter",
    packed: false,
    essential: false,
    not_needed: false,
    link: "link_to_buy_nail_cutter",
    id: "Xn5df3KU1Q",
  },
  {
    category: "PersonalCare",
    name: "Body Lotion",
    packed: false,
    essential: false,
    not_needed: false,
    link: "link_to_buy_body_lotion",
    id: "lhWAdp74hw",
  },
  {
    category: "PersonalCare",
    name: "Deodorant",
    packed: false,
    essential: false,
    not_needed: false,
    link: "link_to_buy_deodorant",
    id: "g0ynU8gXqV",
  },
  {
    category: "PersonalCare",
    name: "Wet Tissues",
    packed: false,
    essential: false,
    not_needed: false,
    link: "link_to_buy_wet_tissues",
    id: "iNiU7pYIOS",
  },
  {
    category: "PersonalCare",
    name: "Conditioner",
    packed: false,
    essential: false,
    not_needed: false,
    link: "link_to_buy_conditioner",
    id: "cYxEceMw2i",
  },
  {
    category: "PersonalCare",
    name: "Earbuds",
    packed: false,
    essential: false,
    not_needed: false,
    link: "link_to_buy_earbuds",
    id: "VC2Z1LwxWT",
  },
  {
    category: "PersonalCare",
    name: "Nail Polish and Remover",
    packed: false,
    essential: false,
    not_needed: false,
    link: "link_to_buy_nail_polish_remover",
    id: "r1DjUtJM6c",
  },
  {
    category: "PersonalCare",
    name: "Jewelry",
    packed: false,
    essential: false,
    not_needed: false,
    link: "link_to_buy_jewelry",
    id: "65kJeDFKkr",
  },
  {
    category: "FoodItems",
    name: "Salt",
    packed: false,
    essential: true,
    not_needed: false,
    link: "link_to_buy_salt",
    id: "YuO9hkn3JJ",
  },
  {
    category: "FoodItems",
    name: "Red Chilli",
    packed: false,
    essential: true,
    not_needed: false,
    link: "link_to_buy_red_chilli",
    id: "a8L33kg3JM",
  },
  {
    category: "FoodItems",
    name: "Turmeric Powder",
    packed: false,
    essential: true,
    not_needed: false,
    link: "link_to_buy_turmeric_powder",
    id: "CiTKIoBohL",
  },
  {
    category: "FoodItems",
    name: "Garam Masala",
    packed: false,
    essential: true,
    not_needed: false,
    link: "link_to_buy_garam_masala",
    id: "230clhhp9c",
  },
  {
    category: "FoodItems",
    name: "Dhaniya Powder",
    packed: false,
    essential: true,
    not_needed: false,
    link: "link_to_buy_dhaniya_powder",
    id: "w4potnJEIk",
  },
  {
    category: "FoodItems",
    name: "Zeera (Cumin Seeds)",
    packed: false,
    essential: true,
    not_needed: false,
    link: "link_to_buy_zeera",
    id: "D0qV6lrmBv",
  },
  {
    category: "FoodItems",
    name: "Black Pepper",
    packed: false,
    essential: true,
    not_needed: false,
    link: "link_to_buy_black_pepper",
    id: "HPccCOWGOl",
  },
  {
    category: "FoodItems",
    name: "Mustard Seeds",
    packed: false,
    essential: true,
    not_needed: false,
    link: "link_to_buy_mustard_seeds",
    id: "rmrrML3xiP",
  },
  {
    category: "FoodItems",
    name: "Garlic Paste",
    packed: false,
    essential: true,
    not_needed: false,
    link: "link_to_buy_garlic_paste",
    id: "ZF0UDpnexV",
  },
  {
    category: "FoodItems",
    name: "Besan",
    packed: false,
    essential: true,
    not_needed: false,
    link: "link_to_buy_besan",
    id: "9RL1bjkGeJ",
  },
  {
    category: "FoodItems",
    name: "Ginger Paste",
    packed: false,
    essential: true,
    not_needed: false,
    link: "link_to_buy_ginger_paste",
    id: "sKjYEHdDso",
  },
  {
    category: "FoodItems",
    name: "Maida",
    packed: false,
    essential: true,
    not_needed: false,
    link: "link_to_buy_maida",
    id: "5ez7DeuiY5",
  },
  {
    category: "FoodItems",
    name: "Rava",
    packed: false,
    essential: true,
    not_needed: false,
    link: "link_to_buy_rava",
    id: "QEks2UovKB",
  },
  {
    category: "FoodItems",
    name: "Coffee / Tea Powder",
    packed: false,
    essential: true,
    not_needed: false,
    link: "link_to_buy_coffee_tea_powder",
    id: "TuVJqkeI8Y",
  },
  {
    category: "FoodItems",
    name: "Homemade Sweets",
    packed: false,
    essential: true,
    not_needed: false,
    link: "link_to_buy_homemade_sweets",
    id: "WCL4O7uM9p",
  },
  {
    category: "FoodItems",
    name: "Snack Items",
    packed: false,
    essential: true,
    not_needed: false,
    link: "link_to_buy_snack_items",
    id: "ArmLWKHe0k",
  },
  {
    category: "FoodItems",
    name: "Tamarind",
    packed: false,
    essential: false,
    not_needed: false,
    link: "link_to_buy_tamarind",
    id: "GhpGe0sWBO",
  },
  {
    category: "FoodItems",
    name: "Chaat Masala",
    packed: false,
    essential: false,
    not_needed: false,
    link: "link_to_buy_chaat_masala",
    id: "eeUIwpV7Vi",
  },
  {
    category: "FoodItems",
    name: "Cinnamon",
    packed: false,
    essential: false,
    not_needed: false,
    link: "link_to_buy_cinnamon",
    id: "An9HfJgJdK",
  },
  {
    category: "FoodItems",
    name: "Jaggery",
    packed: false,
    essential: false,
    not_needed: false,
    link: "link_to_buy_jaggery",
    id: "QxPj8pXPpB",
  },
  {
    category: "FoodItems",
    name: "Cardamom",
    packed: false,
    essential: false,
    not_needed: false,
    link: "link_to_buy_cardamom",
    id: "xGix24sLm4",
  },
  {
    category: "FoodItems",
    name: "Cloves",
    packed: false,
    essential: false,
    not_needed: false,
    link: "link_to_buy_cloves",
    id: "72CjvwOWIz",
  },
  {
    category: "FoodItems",
    name: "Amchur",
    packed: false,
    essential: false,
    not_needed: false,
    link: "link_to_buy_amchur",
    id: "Yh4TJICYdp",
  },
  {
    category: "FoodItems",
    name: "Maggi",
    packed: false,
    essential: false,
    not_needed: false,
    link: "link_to_buy_maggi",
    id: "zD6FvJcOV4",
  },
  {
    category: "FoodItems",
    name: "Papad",
    packed: false,
    essential: false,
    not_needed: false,
    link: "link_to_buy_papad",
    id: "E6LkEdEuCw",
  },
];
