export const essentials = [
  {
    category: "Clothing",
    name: "Formal Clothing",
    packed: false,
    essential: true,
    count: 4,
    link1: "https://amzn.to/3QKMxNo",
    id: "aZQPkMX4pF",
  },
  {
    category: "Clothing",
    name: "Ties (for Men)",
    packed: false,
    essential: true,
    count: 2,
    link1: "https://amzn.to/3QxN9WM",
    id: "YBK0LUkTZn",
  },
  {
    category: "Clothing",
    name: "Undergarments",
    packed: false,
    essential: true,
    count: 10,
    link1: "https://amzn.to/45sXt6q",
    id: "3zxJQHTdJG",
  },
  {
    category: "Clothing",
    name: "Winter Jacket",
    packed: false,
    essential: true,
    count: 2,
    link1: "https://amzn.to/3DVQUhc",
    id: "mFZ3iiE8hn",
  },
  {
    category: "Clothing",
    name: "Rain Coat",
    packed: false,
    essential: true,
    count: 1,
    link1: "https://amzn.to/3OwQK4F",
    id: "UIOWaIRYUZ",
  },
  {
    category: "Clothing",
    name: "Sweaters",
    packed: false,
    essential: true,
    count: 3,
    link1: "https://amzn.to/3KENfrR",
    id: "ntBFjcvQ9w",
  },
  {
    category: "Clothing",
    name: "Nightwear",
    packed: false,
    essential: true,
    count: 4,
    link1: "https://amzn.to/3QCZxoz",
    id: "apmDt0dou2",
  },
  {
    category: "Clothing",
    name: "Jeans",
    packed: false,
    essential: true,
    count: 4,
    link1: "https://amzn.to/45tlAlw",
    id: "y1BFpmZoou",
  },
  {
    category: "Clothing",
    name: "T-shirts",
    packed: false,
    essential: true,
    count: 9,
    link1: "https://amzn.to/3OxXlfk",
    id: "cPNURqdWQX",
  },
  {
    category: "Clothing",
    name: "Gloves",
    packed: false,
    essential: true,
    count: 3,
    link1: "https://amzn.to/3OxXpvA",
    id: "fWhDQehnRn",
  },
  {
    category: "Clothing",
    name: "Bath Towels",
    packed: false,
    essential: true,
    count: 3,
    link1: "https://amzn.to/458tBMY",
    id: "8puEnrbFDn",
  },
  {
    category: "Clothing",
    name: "Thermal Wear",
    packed: false,
    essential: false,
    count: 2,
    link1: "https://amzn.to/3OrdXW0",
    id: "vMNAS9OFST",
  },
  {
    category: "Clothing",
    name: "Scarf/Muffler",
    packed: false,
    essential: false,
    count: 2,
    link1: "https://amzn.to/47yMiLI",
    id: "2C4LBkLwoI",
  },
  {
    category: "Clothing",
    name: "Shorts",
    packed: false,
    essential: false,
    count: 4,
    link1: "https://amzn.to/3OTVwun",
    id: "1VgHfWp7Zk",
  },
  {
    category: "Clothing",
    name: "Swimming Trunks",
    packed: false,
    essential: false,
    count: 1,
    link1: "https://amzn.to/3OQyN2p",
    id: "j2EFjaoix0",
  },
  {
    category: "Clothing",
    name: "Sports Wear",
    packed: false,
    essential: false,
    count: 2,
    link1: "https://amzn.to/4573EgY",
    id: "pvuFVK7IPr",
  },
  {
    category: "Clothing",
    name: "Belts for Pants",
    packed: false,
    essential: false,
    count: 2,
    link1: "https://amzn.to/47soybZ",
    id: "nRmaSrcV50",
  },
  {
    category: "Stationary",
    name: "Cello Tape",
    packed: false,
    essential: true,
    count: 1,
    link1: "https://amzn.to/3s9J9l5",
    id: "BgKs6GTDKE",
  },
  {
    category: "Stationary",
    name: "Pens & Pencils",
    packed: false,
    essential: true,
    count: 5,
    link1: "https://amzn.to/457eQdg",
    id: "QTF2HT1l3Q",
  },
  {
    category: "Stationary",
    name: "Eraser",
    packed: false,
    essential: true,
    count: 2,
    link1: "https://amzn.to/3YwSNKG",
    id: "nCN3cey7in",
  },
  {
    category: "Stationary",
    name: "File Folder",
    packed: false,
    essential: true,
    count: 2,
    link1: "https://amzn.to/44aFCAa",
    id: "qalWoNCjzf",
  },
  {
    category: "Stationary",
    name: "Marker",
    packed: false,
    essential: true,
    count: 1,
    link1: "https://amzn.to/3YC3zj0",
    id: "Z67quQ8vtm",
  },
  {
    category: "Stationary",
    name: "Notebooks / Pads",
    packed: false,
    essential: true,
    count: 4,
    link1: "https://amzn.to/45mc2JL",
    id: "H6CnbWWcfM",
  },
  {
    category: "Stationary",
    name: "Rubber Bands",
    packed: false,
    essential: true,
    count: 1,
    link1: "https://amzn.to/3Yv7kql",
    id: "0rUFxkqD3z",
  },
  {
    category: "Stationary",
    name: "Stapler and Pin",
    packed: false,
    essential: true,
    count: 1,
    link1: "https://amzn.to/449mXVq",
    id: "4sMj4sUmMh",
  },
  {
    category: "Stationary",
    name: "Sticky Notes",
    packed: false,
    essential: true,
    count: 1,
    link1: "https://amzn.to/3Ow0I6t",
    id: "TcvPFdUbFq",
  },
  {
    category: "Stationary",
    name: "Scissors",
    packed: false,
    essential: true,
    count: 1,
    link1: "https://amzn.to/3qzfUaQ",
    id: "X1ipGRNG5K",
  },
  {
    category: "Stationary",
    name: "Paper Clips",
    packed: false,
    essential: true,
    count: 1,
    link1: "https://amzn.to/3KFOKpB",
    id: "uGBYVenTW9",
  },
  {
    category: "Stationary",
    name: "A4 Sheets",
    packed: false,
    essential: true,
    count: 1,
    link1: "https://amzn.to/3qwaugW",
    id: "DyPbZSaWgt",
  },
  {
    category: "Stationary",
    name: "Highlighter",
    packed: false,
    essential: false,
    count: 1,
    link1: "https://amzn.to/3DV3Eoc",
    id: "3HqWwvizIk",
  },
  {
    category: "Stationary",
    name: "Glue",
    packed: false,
    essential: false,
    count: 1,
    link1: "https://amzn.to/3YAda9P",
    id: "UTiUfBAC55",
  },
  {
    category: "Stationary",
    name: "Pen Holder",
    packed: false,
    essential: false,
    count: 1,
    link1: "https://amzn.to/3DWC6z0",
    id: "l4qkQCt5Jx",
  },
  {
    category: "Stationary",
    name: "Punching Machine",
    packed: false,
    essential: false,
    count: 1,
    link1: "https://amzn.to/3QD1gKw",
    id: "FfUzjDvcCX",
  },
  {
    category: "Stationary",
    name: "Paper Cutter",
    packed: false,
    essential: false,
    count: 1,
    link1: "https://amzn.to/47t4JRM",
    id: "QpsYrS99yU",
  },
  {
    category: "Stationary",
    name: "Labels",
    packed: false,
    essential: false,
    count: 1,
    link1: "https://amzn.to/3Yyr24s",
    id: "mulOhvBWEU",
  },
  {
    category: "Stationary",
    name: "Scientific Calculator",
    packed: false,
    essential: false,
    count: 1,
    link1: "https://amzn.to/3KFzfxQ",
    id: "tBrpgO7xXc",
  },
  {
    category: "Stationary",
    name: "Small Ruler",
    packed: false,
    essential: false,
    count: 1,
    link1: "https://amzn.to/3YAVRpl",
    id: "hTqIvhFece",
  },
  {
    category: "Stationary",
    name: "Compass Box / Pouch",
    packed: false,
    essential: false,
    count: 1,
    link1: "https://amzn.to/3OSphfg",
    id: "F2OuU8q938",
  },
  {
    category: "Footwear",
    name: "Formal Shoes",
    packed: false,
    essential: true,
    count: 1,
    link1: "https://amzn.to/3YBmPgA",
    id: "8cOvnyDebU",
  },
  {
    category: "Footwear",
    name: "Sports Shoes",
    packed: false,
    essential: true,
    count: 1,
    link1: "https://amzn.to/3Ow0Y5r",
    id: "ZEmKgM6Pbs",
  },
  {
    category: "Footwear",
    name: "Casual Shoes",
    packed: false,
    essential: true,
    count: 1,
    link1: "https://amzn.to/449X8Vx",
    id: "ZqwPZDRoYR",
  },
  {
    category: "Footwear",
    name: "Indoor Slippers",
    packed: false,
    essential: true,
    count: 1,
    link1: "https://amzn.to/3DSyLRx",
    id: "WdBHGMSfkE",
  },
  {
    category: "Footwear",
    name: "Socks",
    packed: false,
    essential: true,
    count: 8,
    link1: "https://amzn.to/3s9JhB5",
    id: "jKOzT83GV2",
  },
  {
    category: "Footwear",
    name: "Woollen socks (for cold weather)",
    packed: false,
    essential: false,
    count: 2,
    link1: "https://amzn.to/3qA2yLt",
    id: "fyRDW1iD3g",
  },
  {
    category: "Electronics",
    name: "Personal Laptop and Charger",
    packed: false,
    essential: true,
    count: 1,
    link1: "https://amzn.to/3sa72Jo",
    id: "qMRQidTBjN",
  },
  {
    category: "Electronics",
    name: "Mobile Phone and Charger",
    packed: false,
    essential: true,
    count: 1,
    link1: "https://amzn.to/3DSwg1o",
    id: "iRuKwIjxRm",
  },
  {
    category: "Electronics",
    name: "Table Clock with Alarm Functionality",
    packed: false,
    essential: true,
    count: 1,
    link1: "https://amzn.to/44cqLoW",
    id: "rRreWnXvPg",
  },
  {
    category: "Electronics",
    name: "Travel Adaptor",
    packed: false,
    essential: true,
    count: 2,
    link1: "https://amzn.to/3DVBJok",
    id: "0N7ZZHGbII",
  },
  {
    category: "Electronics",
    name: "Spike Buster",
    packed: false,
    essential: true,
    count: 1,
    link1: "https://amzn.to/3QD00Hl",
    id: "jhxsdACqxj",
  },
  {
    category: "Electronics",
    name: "Extra Batteries",
    packed: false,
    essential: true,
    count: 1,
    link1: "https://amzn.to/3Qz4y1l",
    id: "gMXGh4JWeZ",
  },
  {
    category: "Electronics",
    name: "External Harddisk",
    packed: false,
    essential: false,
    count: 1,
    link1: "https://amzn.to/3Qz4JK3",
    id: "LkKze7Bj7k",
  },
  {
    category: "Electronics",
    name: "USB Keyboard and Mouse",
    packed: false,
    essential: false,
    count: 1,
    link1: "https://amzn.to/3QzPcth",
    id: "gEGIsXqHjO",
  },
  {
    category: "Electronics",
    name: "Bluetooth Speakers",
    packed: false,
    essential: false,
    count: 1,
    link1: "https://amzn.to/3QxO8WY",
    id: "SEjaLT3Qu1",
  },
  {
    category: "Electronics",
    name: "Digital Camera",
    packed: false,
    essential: false,
    count: 1,
    link1: "https://amzn.to/3Qz1F0x",
    id: "fhSRYXGzml",
  },
  {
    category: "Electronics",
    name: "Headphones with Mic",
    packed: false,
    essential: false,
    count: 1,
    link1: "https://amzn.to/45uohn9",
    id: "zT5UDr8V9Y",
  },
  {
    category: "Electronics",
    name: "Powerbank",
    packed: false,
    essential: false,
    count: 1,
    link1: "https://amzn.to/45ixw9Q",
    id: "OBXwoW2C2o",
  },
  {
    category: "Electronics",
    name: "LAN Cable",
    packed: false,
    essential: false,
    count: 1,
    link1: "https://amzn.to/45dtkIY",
    id: "NQjdxlDCEe",
  },
  {
    category: "Electronics",
    name: "Tripod",
    packed: false,
    essential: false,
    count: 1,
    link1: "https://amzn.to/3OUkWYZ",
    id: "FH3xqMkqwl",
  },
  {
    category: "Electronics",
    name: "Steam Iron",
    packed: false,
    essential: false,
    count: 1,
    link1: "https://amzn.to/45dtAYs",
    id: "4RsDey6svM",
  },
  {
    category: "Medicine",
    name: "Crocin",
    packed: false,
    essential: true,
    count: 1,
    link1: "",
    id: "WFCGJtye1N",
  },
  {
    category: "Medicine",
    name: "Combiflam",
    packed: false,
    essential: true,
    count: 1,
    link1: "",
    id: "zhpRQBIzVq",
  },
  {
    category: "Medicine",
    name: "Cyclopam",
    packed: false,
    essential: true,
    count: 1,
    link1: "",
    id: "uGFtDAqEDK",
  },
  {
    category: "Medicine",
    name: "Vicks Vaporub",
    packed: false,
    essential: true,
    count: 1,
    link1: "https://amzn.to/45cjJBZ",
    id: "ZcY38FjZSU",
  },
  {
    category: "Medicine",
    name: "Thermometer",
    packed: false,
    essential: true,
    count: 1,
    link1: "https://amzn.to/45KBx7l",
    id: "EWEo5K0obm",
  },
  {
    category: "Medicine",
    name: "Volini Spray",
    packed: false,
    essential: true,
    count: 1,
    link1: "https://amzn.to/3s0QgMz",
    id: "Bw4PRFSb9f",
  },
  {
    category: "Medicine",
    name: "Band-Aids",
    packed: false,
    essential: true,
    count: 1,
    link1: "https://amzn.to/3YAsIKO",
    id: "pqfeSTYrhi",
  },
  {
    category: "Medicine",
    name: "Cotton",
    packed: false,
    essential: true,
    count: 1,
    link1: "https://amzn.to/47pcNDb",
    id: "VvttgIf4FS",
  },
  {
    category: "Medicine",
    name: "Salvol/Dentol",
    packed: false,
    essential: true,
    count: 1,
    link1: "https://amzn.to/45mpfl8",
    id: "B8Bg2oypWR",
  },
  {
    category: "Medicine",
    name: "Prescription Medicines",
    packed: false,
    essential: true,
    count: 1,
    link1: "",
    id: "50PStKv2sZ",
  },
  {
    category: "Medicine",
    name: "Avomine",
    packed: false,
    essential: false,
    count: 1,
    link1: "",
    id: "OV8OwyPstS",
  },
  {
    category: "Medicine",
    name: "Gelucil, Zantac",
    packed: false,
    essential: false,
    count: 1,
    link1: "",
    id: "JxhPHfff3D",
  },
  {
    category: "Medicine",
    name: "Lopomide",
    packed: false,
    essential: false,
    count: 1,
    link1: "",
    id: "xEfF0heVNV",
  },
  {
    category: "Medicine",
    name: "Itch Guard",
    packed: false,
    essential: false,
    count: 1,
    link1: "https://amzn.to/449S7MD",
    id: "XVPel4tXyC",
  },
  {
    category: "Medicine",
    name: "Strepsils",
    packed: false,
    essential: false,
    count: 1,
    link1: "https://amzn.to/3YvFAln",
    id: "S5HoLpINKh",
  },
  {
    category: "Medicine",
    name: "Burnol",
    packed: false,
    essential: false,
    count: 1,
    link1: "https://amzn.to/3YyrsI4",
    id: "nZoRW1Y7Fs",
  },
  {
    category: "Medicine",
    name: "Inhaler",
    packed: false,
    essential: false,
    count: 1,
    link1: "https://amzn.to/45t9qJI",
    id: "BsClWrZeUe",
  },
  {
    category: "Medicine",
    name: "Benadryl",
    packed: false,
    essential: false,
    count: 1,
    link1: "",
    id: "e3hCneY51W",
  },
  {
    category: "Kitchen",
    name: "Pressure Cooker",
    packed: false,
    essential: true,
    count: 1,
    link1: "https://amzn.to/3OCPTPY",
    id: "f9jxHVKCkt",
  },
  {
    category: "Kitchen",
    name: "Medium-Sized Pan for Cooking Vegetables",
    packed: false,
    essential: true,
    count: 1,
    link1: "https://amzn.to/3OC3qHL",
    id: "69ErOR8Ped",
  },
  {
    category: "Kitchen",
    name: "Serving Spoons of Various Sizes",
    packed: false,
    essential: true,
    count: 1,
    link1: "https://amzn.to/45cjQgT",
    id: "1q95BEVhOZ",
  },
  {
    category: "Kitchen",
    name: "Plates",
    packed: false,
    essential: true,
    count: 2,
    link1: "https://amzn.to/45iy6V4",
    id: "VxNWOYNnAb",
  },
  {
    category: "Kitchen",
    name: "Kadhai for boiling milk/water/rice",
    packed: false,
    essential: true,
    count: 1,
    link1: "https://amzn.to/3KFzCse",
    id: "BmdMLYK8Ys",
  },
  {
    category: "Kitchen",
    name: "Knives",
    packed: false,
    essential: true,
    count: 1,
    link1: "https://amzn.to/3KGuPH4",
    id: "A1ISicmoQB",
  },
  {
    category: "Kitchen",
    name: "Stainless Steel Glasses/Tumblers",
    packed: false,
    essential: true,
    count: 1,
    link1: "https://amzn.to/3KEOdEv",
    id: "z5Niz1rlQ5",
  },
  {
    category: "Kitchen",
    name: "Normal Small Spoons and Forks",
    packed: false,
    essential: true,
    count: 1,
    link1: "https://amzn.to/3qtf3sf",
    id: "KvHMzHqemN",
  },
  {
    category: "Kitchen",
    name: "Water Bottles",
    packed: false,
    essential: true,
    count: 1,
    link1: "https://amzn.to/3sbbQOE",
    id: "jsgytTdql5",
  },
  {
    category: "Kitchen",
    name: "Lunchbox",
    packed: false,
    essential: true,
    count: 1,
    link1: "https://amzn.to/3KJ8rgj",
    id: "THKwdGj4VU",
  },
  {
    category: "Kitchen",
    name: "Can Opener",
    packed: false,
    essential: true,
    count: 1,
    link1: "https://amzn.to/3ql6Er2",
    id: "01DzbdNmcV",
  },
  {
    category: "Kitchen",
    name: "Bowls",
    packed: false,
    essential: true,
    count: 3,
    link1: "https://amzn.to/3KFtel7",
    id: "clauJKIrQU",
  },
  {
    category: "Kitchen",
    name: "Extra Weights and Gaskets for Cookers",
    packed: false,
    essential: false,
    count: 1,
    link1: "https://amzn.to/3KCqIvC",
    id: "JBssOWKmOe",
  },
  {
    category: "Kitchen",
    name: "Roti Pad & Rolling Pin",
    packed: false,
    essential: false,
    count: 1,
    link1: "https://amzn.to/3QCupVW",
    id: "nC6NSnKvIJ",
  },
  {
    category: "Kitchen",
    name: "Butter Knives",
    packed: false,
    essential: false,
    count: 1,
    link1: "https://amzn.to/3ql6VKA",
    id: "D8veMbFOQf",
  },
  {
    category: "Kitchen",
    name: "Vegetable Chopping Board",
    packed: false,
    essential: false,
    count: 1,
    link1: "https://amzn.to/3YBnfUc",
    id: "zehGyJZmNg",
  },
  {
    category: "Kitchen",
    name: "Strainers of Various Sizes",
    packed: false,
    essential: false,
    count: 1,
    link1: "https://amzn.to/3OXRMbC",
    id: "Ch6T0etrex",
  },
  {
    category: "Kitchen",
    name: "Microwave-safe utensils",
    packed: false,
    essential: false,
    count: 1,
    link1: "https://amzn.to/3YyrJe4",
    id: "ftzSgkk8mk",
  },
  {
    category: "Kitchen",
    name: "Vegetable Cutter / Dicer",
    packed: false,
    essential: false,
    count: 1,
    link1: "https://amzn.to/3sfIw9v",
    id: "4jYiATYQ0R",
  },
  {
    category: "Kitchen",
    name: "Small Mixer",
    packed: false,
    essential: false,
    count: 1,
    link1: "https://amzn.to/3DWDdPc",
    id: "MUS85efpA1",
  },
  {
    category: "PersonalCare",
    name: "Soap Box",
    packed: false,
    essential: true,
    count: 1,
    link1: "https://amzn.to/3sfs1KE",
    id: "5w2nluHTHq",
  },
  {
    category: "PersonalCare",
    name: "Hand Sanitizer",
    packed: false,
    essential: true,
    count: 1,
    link1: "https://amzn.to/44YtCDf",
    id: "vLYLcExsqe",
  },
  {
    category: "PersonalCare",
    name: "Hand Wash",
    packed: false,
    essential: true,
    count: 1,
    link1: "https://amzn.to/445Z8Ow",
    id: "ZzC5nvwQ8b",
  },
  {
    category: "PersonalCare",
    name: "Hair Oil",
    packed: false,
    essential: true,
    count: 1,
    link1: "https://amzn.to/3s7EPTs",
    id: "J9kAkTsDbB",
  },
  {
    category: "PersonalCare",
    name: "Shampoo",
    packed: false,
    essential: true,
    count: 1,
    link1: "https://amzn.to/4550ZnL",
    id: "slRCNxJYeM",
  },
  {
    category: "PersonalCare",
    name: "Tooth Paste",
    packed: false,
    essential: true,
    count: 1,
    link1: "https://amzn.to/3sbJ94b",
    id: "GlDCWtuKhr",
  },
  {
    category: "PersonalCare",
    name: "Tooth Brush",
    packed: false,
    essential: true,
    count: 2,
    link1: "https://amzn.to/457agfk",
    id: "4bR64bMpOv",
  },
  {
    category: "PersonalCare",
    name: "Soap",
    packed: false,
    essential: true,
    count: 2,
    link1: "https://amzn.to/3sd0SYX",
    id: "DHPjQBJhOY",
  },
  {
    category: "PersonalCare",
    name: "Tissues",
    packed: false,
    essential: true,
    count: 1,
    link1: "https://amzn.to/3sbJcgn",
    id: "SxBY87Fix1",
  },
  {
    category: "PersonalCare",
    name: "Face Wash",
    packed: false,
    essential: true,
    count: 1,
    link1: "https://amzn.to/47sgyYl",
    id: "0ZJcKCq2iT",
  },
  {
    category: "PersonalCare",
    name: "Moisturizer",
    packed: false,
    essential: true,
    count: 1,
    link1: "https://amzn.to/3DWRF9C",
    id: "DihsZHkHth",
  },
  {
    category: "PersonalCare",
    name: "Sun Screen",
    packed: false,
    essential: true,
    count: 1,
    link1: "https://amzn.to/3EeeIgB",
    id: "OgE14O16lP",
  },
  {
    category: "PersonalCare",
    name: "Lip Balm",
    packed: false,
    essential: true,
    count: 1,
    link1: "https://amzn.to/45KBZCz",
    id: "f3DkNmRXeZ",
  },
  {
    category: "PersonalCare",
    name: "Hair Comb",
    packed: false,
    essential: true,
    count: 1,
    link1: "https://amzn.to/3s58OeB",
    id: "rA6ehzQhPV",
  },
  {
    category: "PersonalCare",
    name: "Rubber Bands",
    packed: false,
    essential: true,
    count: 1,
    link1: "https://amzn.to/3KJ8QPR",
    id: "n3dUSNfNaJ",
  },
  {
    category: "PersonalCare",
    name: "Shaving Razor and Foam",
    packed: false,
    essential: true,
    count: 1,
    link1: "https://amzn.to/3qrUjRP",
    id: "4Fbg4U8um4",
  },
  {
    category: "PersonalCare",
    name: "Hair Pins",
    packed: false,
    essential: true,
    count: 1,
    link1: "https://amzn.to/3OSMEW4",
    id: "PvcKNSV6lb",
  },
  {
    category: "PersonalCare",
    name: "Hair Clips / Bands",
    packed: false,
    essential: true,
    count: 1,
    link1: "https://amzn.to/3OUltdp",
    id: "As28cEYLKR",
  },
  {
    category: "PersonalCare",
    name: "Nail Cutter",
    packed: false,
    essential: false,
    count: 1,
    link1: "https://amzn.to/3QKTxKa",
    id: "7nRK8sCPop",
  },
  {
    category: "PersonalCare",
    name: "Body Lotion",
    packed: false,
    essential: false,
    count: 1,
    link1: "https://amzn.to/3DSSoc7",
    id: "X4DQq5q2ay",
  },
  {
    category: "PersonalCare",
    name: "Deodorant",
    packed: false,
    essential: false,
    count: 1,
    link1: "https://amzn.to/3DVaV7u",
    id: "78h75ja3GI",
  },
  {
    category: "PersonalCare",
    name: "Wet Tissues",
    packed: false,
    essential: false,
    count: 1,
    link1: "https://amzn.to/3KEUUGD",
    id: "V1kddVTF8o",
  },
  {
    category: "PersonalCare",
    name: "Conditioner",
    packed: false,
    essential: false,
    count: 1,
    link1: "https://amzn.to/3OxEn8w",
    id: "p6fzGKpGFD",
  },
  {
    category: "PersonalCare",
    name: "Ear Swabs",
    packed: false,
    essential: false,
    count: 1,
    link1: "https://amzn.to/3QE8Kge",
    id: "iBdf2W7VAx",
  },
  {
    category: "PersonalCare",
    name: "Nail Polish and Remover",
    packed: false,
    essential: false,
    count: 1,
    link1: "https://amzn.to/457o6ye",
    id: "INKDhW1O8v",
  },
  {
    category: "PersonalCare",
    name: "Jewelry",
    packed: false,
    essential: false,
    count: 1,
    link1: "https://amzn.to/3qtyuRI",
    id: "YzcgbjnzWF",
  },
  {
    category: "FoodItems",
    name: "Salt",
    packed: false,
    essential: true,
    count: 1,
    link1: "https://amzn.to/455Kubm",
    id: "OFVfxyTGRX",
  },
  {
    category: "FoodItems",
    name: "Red Chilli",
    packed: false,
    essential: true,
    count: 1,
    link1: "https://amzn.to/3OWfNQi",
    id: "73BSjy9zex",
  },
  {
    category: "FoodItems",
    name: "Turmeric Powder",
    packed: false,
    essential: true,
    count: 1,
    link1: "https://amzn.to/3KAPfkX",
    id: "ovsx4mTQvs",
  },
  {
    category: "FoodItems",
    name: "Garam Masala",
    packed: false,
    essential: true,
    count: 1,
    link1: "https://amzn.to/3sfyt4k",
    id: "y972xXIHBw",
  },
  {
    category: "FoodItems",
    name: "Dhaniya Powder",
    packed: false,
    essential: true,
    count: 1,
    link1: "https://amzn.to/457X8GD",
    id: "lRUVKBJj91",
  },
  {
    category: "FoodItems",
    name: "Zeera (Cumin Seeds)",
    packed: false,
    essential: true,
    count: 1,
    link1: "https://amzn.to/3DTDMJl",
    id: "JjcRZFNKZK",
  },
  {
    category: "FoodItems",
    name: "Black Pepper",
    packed: false,
    essential: true,
    count: 1,
    link1: "https://amzn.to/45t5GaK",
    id: "QAAYGJLajK",
  },
  {
    category: "FoodItems",
    name: "Mustard Seeds",
    packed: false,
    essential: true,
    count: 1,
    link1: "https://amzn.to/3qtm1NV",
    id: "31kh5Q2adK",
  },
  {
    category: "FoodItems",
    name: "Garlic Paste",
    packed: false,
    essential: true,
    count: 1,
    link1: "https://amzn.to/47J8OSb",
    id: "pcKkQdfO4r",
  },
  {
    category: "FoodItems",
    name: "Besan",
    packed: false,
    essential: true,
    count: 1,
    link1: "https://amzn.to/3s7UmTo",
    id: "bihx8rqVBH",
  },
  {
    category: "FoodItems",
    name: "Ginger Paste",
    packed: false,
    essential: true,
    count: 1,
    link1: "https://amzn.to/3sd8lHt",
    id: "9B8cuAnzxl",
  },
  {
    category: "FoodItems",
    name: "Maida",
    packed: false,
    essential: true,
    count: 1,
    link1: "https://amzn.to/3YyuZpI",
    id: "uEQEFnZrXx",
  },
  {
    category: "FoodItems",
    name: "Rava",
    packed: false,
    essential: true,
    count: 1,
    link1: "https://amzn.to/47yC3GY",
    id: "n3RKwsZ1X7",
  },
  {
    category: "FoodItems",
    name: "Coffee / Tea Powder",
    packed: false,
    essential: true,
    count: 1,
    link1: "https://amzn.to/47toOHH",
    id: "oTwFni4OVc",
  },
  {
    category: "FoodItems",
    name: "Homemade Sweets",
    packed: false,
    essential: true,
    count: 1,
    link1: "",
    id: "6clA5JAkEj",
  },
  {
    category: "FoodItems",
    name: "Snack Items",
    packed: false,
    essential: true,
    count: 1,
    link1: "https://amzn.to/47sVKQz",
    id: "xVJAPDkSVw",
  },
  {
    category: "FoodItems",
    name: "Tamarind",
    packed: false,
    essential: false,
    count: 1,
    link1: "https://amzn.to/3Oy4j3Y",
    id: "CNEvXJcWd3",
  },
  {
    category: "FoodItems",
    name: "Chaat Masala",
    packed: false,
    essential: false,
    count: 1,
    link1: "https://amzn.to/3DWAHrY",
    id: "i5mgowhGPt",
  },
  {
    category: "FoodItems",
    name: "Cinnamon",
    packed: false,
    essential: false,
    count: 1,
    link1: "https://amzn.to/3OGNLHc",
    id: "txp05efKZd",
  },
  {
    category: "FoodItems",
    name: "Jaggery",
    packed: false,
    essential: false,
    count: 1,
    link1: "https://amzn.to/3OANd5h",
    id: "eBEBw1vGXX",
  },
  {
    category: "FoodItems",
    name: "Cardamom",
    packed: false,
    essential: false,
    count: 1,
    link1: "https://amzn.to/3OrdmU4",
    id: "duDBFKR7E3",
  },
  {
    category: "FoodItems",
    name: "Cloves",
    packed: false,
    essential: false,
    count: 1,
    link1: "https://amzn.to/3DWdp5O",
    id: "21vQTDFNY3",
  },
  {
    category: "FoodItems",
    name: "Amchur",
    packed: false,
    essential: false,
    count: 1,
    link1: "https://amzn.to/45qpbkj",
    id: "wplcnvRMDK",
  },
  {
    category: "FoodItems",
    name: "Maggi",
    packed: false,
    essential: false,
    count: 3,
    link1: "https://amzn.to/3DSMk3e",
    id: "dXe2EbahLN",
  },
  {
    category: "FoodItems",
    name: "Papad",
    packed: false,
    essential: false,
    count: 1,
    link1: "https://amzn.to/3qvTIhT",
    id: "md4oU5LMa0",
  },
  {
    category: "Miscellaneous",
    count: 1,
    name: "Umbrella",
    packed: false,
    essential: true,
    link1: "https://amzn.to/3OTThqW",
    id: "euj9ScMFYY",
  },
  {
    category: "Miscellaneous",
    count: 1,
    name: "Handkerchiefs",
    packed: false,
    essential: true,
    link1: "https://amzn.to/4540Kte",
    id: "GYrsPUomb6",
  },
  {
    category: "Miscellaneous",
    count: 1,
    name: "Bedsheets",
    packed: false,
    essential: true,
    link1: "https://amzn.to/3KGtXCy",
    id: "wTWK6yj1Z9",
  },
  {
    category: "Miscellaneous",
    count: 1,
    name: "Blankets",
    packed: false,
    essential: true,
    link1: "https://amzn.to/3OWgkBM",
    id: "XYQ0jbrV3s",
  },
  {
    category: "Miscellaneous",
    count: 2,
    name: "Pillow Covers",
    packed: false,
    essential: true,
    link1: "https://amzn.to/3OBIa4C",
    id: "2bQx0HrKvA",
  },
  {
    category: "Miscellaneous",
    count: 1,
    name: "Wallet/Purse",
    packed: false,
    essential: true,
    link1: "https://amzn.to/456Ab6R",
    id: "41uO8sur9h",
  },
  {
    category: "Miscellaneous",
    count: 1,
    name: "Spectacles (take an extra pair)",
    packed: false,
    essential: true,
    link1: "",
    id: "ixVwl5dp7A",
  },
  {
    category: "Miscellaneous",
    count: 1,
    name: "Backpack",
    packed: false,
    essential: true,
    link1: "https://amzn.to/3KBrqcE",
    id: "kbwl8tQ3lt",
  },
  {
    category: "Miscellaneous",
    count: 1,
    name: "Safety Pins",
    packed: false,
    essential: true,
    link1: "https://amzn.to/448ZDHz",
    id: "fnNVnx3Pmy",
  },
  {
    category: "Miscellaneous",
    count: 1,
    name: "Zip Locks",
    packed: false,
    essential: true,
    link1: "https://amzn.to/3OUmMJl",
    id: "JHyxl0CgT3",
  },
  {
    category: "Miscellaneous",
    count: 5,
    name: "Hangers",
    packed: false,
    essential: true,
    link1: "https://amzn.to/3s7UJ0e",
    id: "0EVp4equ9A",
  },
  {
    category: "Miscellaneous",
    count: 1,
    name: "Sunglasses",
    packed: false,
    essential: false,
    link1: "https://amzn.to/44a4Rmv",
    id: "u1FMmstBFm",
  },
  {
    category: "Miscellaneous",
    count: 1,
    name: "Shoe Polish and Accessories",
    packed: false,
    essential: false,
    link1: "https://amzn.to/4430UQo",
    id: "UmJnNxx4Dx",
  },
  {
    category: "Miscellaneous",
    count: 1,
    name: "Watch",
    packed: false,
    essential: false,
    link1: "https://amzn.to/3qrVQax",
    id: "32qHKr7LJq",
  },
  {
    category: "Miscellaneous",
    count: 1,
    name: "Caps",
    packed: false,
    essential: false,
    link1: "https://amzn.to/3Yx3bSA",
    id: "f2AsR6VZuG",
  },
  {
    category: "Miscellaneous",
    count: 1,
    name: "Handbag",
    packed: false,
    essential: false,
    link1: "https://amzn.to/447Owys",
    id: "i5dGtFqhbz",
  },
  {
    category: "Miscellaneous",
    count: 1,
    name: "Sewing Kit",
    packed: false,
    essential: false,
    link1: "https://amzn.to/3QDrVXr",
    id: "Ps0a5VvEZI",
  },
  {
    category: "Miscellaneous",
    count: 1,
    name: "Keychains",
    packed: false,
    essential: false,
    link1: "https://amzn.to/449650Y",
    id: "398lQE8qMd",
  },
];
